name: 'upload-docker'
description: >
  Simplified the process of building and uploading docker images.
  Created for personal repository work and CI/CD support.

inputs:
  context:
    description: 'Dockerfile path'
    required: true
  repository:
    description: 'Docker hub repository'
    required: true
  release:
    description: 'Release version number.'
    required: true
  username:
    description: 'Docker hub ID'
    required: true
  password:
    description: 'Docker hub PASSWORD'
    required: true
 
runs:
  using: 'composite'
  steps:
    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: 'Build and push'
      uses: docker/build-push-action@v4
      with:
        context: '{{defaultContext}}:${{ inputs.context }}'
        file: Dockerfile
        push: true
        tags: ${{ inputs.username }}/${{ inputs.repository }}:${{ inputs.release }}

branding:
  icon: 'arrow-up-circle'
  color: 'blue'
