name: 'upload-docker'
desctiption: 'docker build and push'

inputs:
  distro:
    desctiption: 'Docker image distro'
    required: true
  path:
    desctiption: 'Dockerfile path'
    required: true
  username:
    desctiption: 'Docker hub ID'
    required: true
  password:
    desctiption: 'Docker hub PASSWORD'
    required: true
  repo:
    desctiption: 'Docker hub repository'
    required: true
  release: # release is optional. default: "v".
    desctiption: 'Release version number. "v" is already included.'

runs:
  using: 'composite'
  steps:
    - name: 'Set up QEMU'
      uses: docker/setup-qemu-action@v2

    - name: 'Set up Docker Buildx'
      uses: docker/setup-buildx-action@v2

    - name: 'Login to Docker Hub'
      uses: docker/login-action@v2
      with:
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: 'Build and push'
      uses: docker/build-push-action@v4
      with:
        context: '{{defaultContext}}:${{ inputs.path }}'
        file: Dockerfile
        push: true
        tags: ${{ inputs.username }}/${{ inputs.repo }}:${{ inputs.distro }}-v${{ inputs.release }}
